markdown: rdiscount
pygments: true

exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock

author:
  name: Benson Lim

title: Hope Caleb
url: http://hopecaleb.com
disqus_id: hopecaleb
feed_url: http://hopecaleb.com/atom.xml
